name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install required packages
      run: sudo apt install podman build-essential qemu-user qemu-user-static  
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag quay.io/rcook/myapp --platform="linux/arm64" --build-arg ARCH=arm64

    - name: login to quay
      run: docker login quay.io -u ${{ secrets.QUAY_USER }} -p ${{ secrets.QUAY_PASSWORD }}

    - name: push to quay
      run: docker push quay.io/rcook/myapp