name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install required packages
      run: sudo apt install podman build-essential qemu-user qemu-user-static  
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag quay.io/rcook/myapp --platform="linux/arm64" --build-arg ARCH=arm64

    - name: Login to Quay
      uses: docker/login-action@v1
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USER }}
        password: ${{ secrets.QUAY_PASSWORD }}

    - name: push to quay
      run: docker push quay.io/rcook/myapp

    - name: Invoke deployment hook Ohio
      uses: distributhor/workflow-webhook@v3
      env:
        webhook_url: ${{ secrets.WEBHOOK_URL_OHIO }}
        webhook_secret: ${{ secrets.WEBHOOK_SECRET_OHIO }}

    - name: Invoke deployment hook Oregon
      uses: distributhor/workflow-webhook@v3
      env:
        webhook_url: ${{ secrets.WEBHOOK_URL_ORE }}
        webhook_secret: ${{ secrets.WEBHOOK_SECRET_ORE }}